---
# GOLANG vars

go_version: 1.14.3
GOPATH: /root/go
GO111MODULE: "on"
golang_shell_profile: /root/.bash_profile

# Download ko
go_get:
- name: ko
  url: github.com/google/ko/cmd/ko
  modules: false

# Download in-toto-golang
go_get:
- name: in-toto-golang
  url: github.com/in-toto/in-toto-golang
  modules: true

# Enviroment variables
os_environment:
  - key: KO_DOCKER_REPO
    value : localhost:5000/mypipeline

# Download hashes
kind_version: v0.8.1
kind_hash: 781c3db479b805d161b7c2c7a31896d1a504b583ebfcce8fcd49538c684d96bc

kubectl_version: v1.18.3
kubectl_hash: 6fcf70aae5bc64870c358fac153cdfdc93f55d8bae010741ecce06bb14c083ea

tkn_version: 0.9.0
tkn_hash: b070f458398deb9f81eff93858b61aa0303e9c38972fadc2b3a03ccb7175a267

# repo data
in-toto-branch: master
secure-supply-chain-branch: master

# user account
cnssc_effective_user_id: root
cnssc_effective_group_id: root

# github account
github_user_id: someuser
